@server = http://localhost:3000

###
GET {{server}}/games HTTP/1.1
content-type: application/json

###
POST {{server}}/games HTTP/1.1
content-type: application/json

{
    "title": "Halo",
    "description": "FPS"
}

###
PATCH {{server}}/games/3692d80eb9d7 HTTP/1.1
content-type: application/json

{
    "description": "FPS 3"
//    "creation_dt": "test"
}

